name: hotdeal-bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install python packages
        run: |
          pip install requests
          pip install beautifulsoup4

      - name: run bot
        run: python bot.py
